NAME= megaphone
SRC= megaphone.cpp
CC= g++
CFLAGS= -Wall -Wextra -Werror

all: $(NAME)

$(NAME): $(SRC)
	$(CC) $(CFLAGS) $(SRC) -o $(NAME)

clean: rm -rf $(NAME)

fclean: clean

re: fclean all

.PHONY: all fclean clean re

